// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pokemon_discord_bot.Data;

#nullable disable

namespace pokemon_discord_bot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115182443_AddFrameTable")]
    partial class AddFrameTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "biome_type", new[] { "forest", "water", "grassland", "cave", "urban", "mountain", "desert" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pokemon_gender", new[] { "male", "female", "genderless" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyReward", b =>
                {
                    b.Property<int>("DailyRewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyRewardId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("DailyRewardId");

                    b.ToTable("daily_rewards");

                    b.HasData(
                        new
                        {
                            DailyRewardId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyRewardClaim", b =>
                {
                    b.Property<int>("DailyClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyClaimId"));

                    b.Property<DateOnly>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<int>("DailyRewardId")
                        .HasColumnType("integer")
                        .HasColumnName("daily_reward_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("DailyClaimId");

                    b.HasIndex("DailyRewardId");

                    b.HasIndex("UserId", "ClaimedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("daily_reward_claims");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyRewardItem", b =>
                {
                    b.Property<int>("DailyRewardItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DailyRewardItemId"));

                    b.Property<int>("DailyRewardId")
                        .HasColumnType("integer")
                        .HasColumnName("daily_reward_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("DailyRewardItemId");

                    b.HasIndex("DailyRewardId");

                    b.HasIndex("ItemId");

                    b.ToTable("daily_reward_items");

                    b.HasData(
                        new
                        {
                            DailyRewardItemId = 1,
                            DailyRewardId = 1,
                            ItemId = 1,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.EncounterEvent", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncounterId"));

                    b.Property<int?>("Biome")
                        .HasColumnType("integer")
                        .HasColumnName("biome");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("TriggeredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("triggered_by");

                    b.HasKey("EncounterId");

                    b.ToTable("encounter_events");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Frame", b =>
                {
                    b.Property<int>("FrameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("frame_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FrameId"));

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("tradeable");

                    b.HasKey("FrameId");

                    b.ToTable("frames");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<Dictionary<string, object>>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<float>("DropChance")
                        .HasColumnType("real")
                        .HasColumnName("drop_chance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("tradeable");

                    b.HasKey("ItemId");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Attributes = new Dictionary<string, object> { ["CatchRateMultiplier"] = 1f },
                            DropChance = 0.1f,
                            Name = "Pokeball",
                            Tradeable = true
                        },
                        new
                        {
                            ItemId = 2,
                            Attributes = new Dictionary<string, object> { ["CatchRateMultiplier"] = 1.2f },
                            DropChance = 0.1f,
                            Name = "Great Ball",
                            Tradeable = true
                        },
                        new
                        {
                            ItemId = 3,
                            Attributes = new Dictionary<string, object> { ["CatchRateMultiplier"] = 1.5f },
                            DropChance = 0.1f,
                            Name = "Ultra Ball",
                            Tradeable = true
                        },
                        new
                        {
                            ItemId = 4,
                            Attributes = new Dictionary<string, object> { ["CatchRateMultiplier"] = 1f },
                            DropChance = 0.1f,
                            Name = "Love Ball",
                            Tradeable = true
                        },
                        new
                        {
                            ItemId = 5,
                            Attributes = new Dictionary<string, object> { ["GuaranteedCatch"] = true },
                            DropChance = 0.1f,
                            Name = "Master Ball",
                            Tradeable = true
                        });
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PlayerInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int?>("FrameId")
                        .HasColumnType("integer")
                        .HasColumnName("frame_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("InventoryId");

                    b.HasIndex("FrameId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_inventory_player");

                    b.ToTable("player_inventory");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PokemonId"));

                    b.Property<int>("ApiPokemonId")
                        .HasColumnType("integer")
                        .HasColumnName("api_pokemon_id");

                    b.Property<long>("CaughtBy")
                        .HasColumnType("bigint")
                        .HasColumnName("caught_by");

                    b.Property<int?>("CaughtWith")
                        .HasColumnType("integer")
                        .HasColumnName("caught_with");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EncounterEventId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_event_id");

                    b.Property<int?>("FrameId")
                        .HasColumnType("integer")
                        .HasColumnName("frame_id");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shiny");

                    b.Property<long>("OwnedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("owned_by");

                    b.Property<int>("PokemonStatsId")
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_stats_id");

                    b.HasKey("PokemonId");

                    b.HasIndex("CaughtWith");

                    b.HasIndex("EncounterEventId");

                    b.HasIndex("FrameId");

                    b.HasIndex("OwnedBy")
                        .HasDatabaseName("idx_pokemon_owned_by");

                    b.HasIndex("PokemonStatsId");

                    b.ToTable("pokemons");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PokemonStats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stats_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatsId"));

                    b.Property<short>("IvAtk")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_atk");

                    b.Property<short>("IvDef")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_def");

                    b.Property<short>("IvHp")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_hp");

                    b.Property<short>("IvSpAtk")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_sp_atk");

                    b.Property<short>("IvSpDef")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_sp_def");

                    b.Property<short>("IvSpeed")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_speed");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasColumnName("size");

                    b.HasKey("StatsId");

                    b.ToTable("pokemon_stats");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyRewardClaim", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.DailyReward", "DailyReward")
                        .WithMany()
                        .HasForeignKey("DailyRewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyReward");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyRewardItem", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.DailyReward", "DailyReward")
                        .WithMany("Items")
                        .HasForeignKey("DailyRewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pokemon_discord_bot.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyReward");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PlayerInventory", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.Frame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId");

                    b.HasOne("pokemon_discord_bot.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Pokemon", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.Item", "CaughtWithItem")
                        .WithMany()
                        .HasForeignKey("CaughtWith");

                    b.HasOne("pokemon_discord_bot.Data.EncounterEvent", "EncounterEvent")
                        .WithMany("Pokemons")
                        .HasForeignKey("EncounterEventId");

                    b.HasOne("pokemon_discord_bot.Data.Frame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId");

                    b.HasOne("pokemon_discord_bot.Data.PokemonStats", "PokemonStats")
                        .WithMany()
                        .HasForeignKey("PokemonStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaughtWithItem");

                    b.Navigation("EncounterEvent");

                    b.Navigation("Frame");

                    b.Navigation("PokemonStats");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.DailyReward", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.EncounterEvent", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
