// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokemonBot.Data;

#nullable disable

namespace pokemon_discord_bot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "biome_type", new[] { "forest", "water", "grassland", "cave", "urban", "mountain", "desert" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pokemon_gender", new[] { "male", "female", "genderless" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pokemon_discord_bot.Data.EncounterEvent", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncounterId"));

                    b.Property<int?>("Biome")
                        .HasColumnType("integer")
                        .HasColumnName("biome");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("TriggeredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("triggered_by");

                    b.HasKey("EncounterId");

                    b.ToTable("encounter_events");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<float>("DropChance")
                        .HasColumnType("real")
                        .HasColumnName("drop_chance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("tradeable");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.ItemAttributes", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttributeId"));

                    b.Property<Dictionary<string, object>>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("AttributeId");

                    b.HasIndex("ItemId");

                    b.ToTable("item_attributes");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PlayerInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("InventoryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("idx_inventory_player");

                    b.ToTable("player_inventory");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PokemonId"));

                    b.Property<int>("ApiPokemonId")
                        .HasColumnType("integer")
                        .HasColumnName("api_pokemon_id");

                    b.Property<long>("CaughtBy")
                        .HasColumnType("bigint")
                        .HasColumnName("caught_by");

                    b.Property<int?>("CaughtWith")
                        .HasColumnType("integer")
                        .HasColumnName("caught_with");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EncounterEventId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_event_id");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shiny");

                    b.Property<long>("OwnedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("owned_by");

                    b.Property<int>("PokemonStatsId")
                        .HasColumnType("integer")
                        .HasColumnName("pokemon_stats_id");

                    b.HasKey("PokemonId");

                    b.HasIndex("CaughtWith");

                    b.HasIndex("EncounterEventId");

                    b.HasIndex("OwnedBy")
                        .HasDatabaseName("idx_pokemon_owned_by");

                    b.HasIndex("PokemonStatsId");

                    b.ToTable("pokemons");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PokemonStats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stats_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatsId"));

                    b.Property<short>("IvAtk")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_atk");

                    b.Property<short>("IvDef")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_def");

                    b.Property<short>("IvHp")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_hp");

                    b.Property<short>("IvSpAtk")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_sp_atk");

                    b.Property<short>("IvSpDef")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_sp_def");

                    b.Property<short>("IvSpeed")
                        .HasColumnType("smallint")
                        .HasColumnName("iv_speed");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasColumnName("size");

                    b.HasKey("StatsId");

                    b.ToTable("pokemon_stats");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.ItemAttributes", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.PlayerInventory", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("pokemon_discord_bot.Data.Pokemon", b =>
                {
                    b.HasOne("pokemon_discord_bot.Data.Item", "CaughtWithItem")
                        .WithMany()
                        .HasForeignKey("CaughtWith");

                    b.HasOne("pokemon_discord_bot.Data.EncounterEvent", "EncounterEvent")
                        .WithMany()
                        .HasForeignKey("EncounterEventId");

                    b.HasOne("pokemon_discord_bot.Data.PokemonStats", "PokemonStats")
                        .WithMany()
                        .HasForeignKey("PokemonStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaughtWithItem");

                    b.Navigation("EncounterEvent");

                    b.Navigation("PokemonStats");
                });
#pragma warning restore 612, 618
        }
    }
}
